In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score

In [2]:
df = pd.read_csv("/content/drive/My Drive/DataSets/bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

In [3]:
df.shape

(7120, 108)

In [4]:
df['location_Marathahalli'].value_counts()

0    7004
1     116
Name: location_Marathahalli, dtype: int64

## Split the features and level

In [5]:
features = df.drop(labels=["price"],axis=1)
level = df["price"]

In [6]:
xtrain,xtest,ytrain,ytest = train_test_split(features,level,test_size = 0.3,random_state = 2021)

In [7]:
print("Shape of xtrain: ",xtrain.shape)
print("Shape of ytrain: ",ytrain.shape)
print("Shape of xtest: ",xtest.shape)
print("Shape of ytest: ",ytest.shape)

Shape of xtrain:  (4984, 107)
Shape of ytrain:  (4984,)
Shape of xtest:  (2136, 107)
Shape of ytest:  (2136,)


## Create the **Model**

In [8]:
regressior_model = DecisionTreeRegressor(criterion="mse") # mse = mean squaired error
regressior_model.fit(xtrain,ytrain)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [9]:
print("Accuracy: ", round(regressior_model.score(X=xtest,y=ytest),ndigits=3)*100,"%")

Accuracy:  91.9 %


In [10]:
# try another criterion="mae" its also called cost_function
regressior_model2 = DecisionTreeRegressor(criterion="mae") # mean absolute error
regressior_model2.fit(xtrain,ytrain)
print("Accuracy: ", round(regressior_model2.score(X=xtest,y=ytest),ndigits=3)*100,"%")

Accuracy:  93.8 %


In [11]:
# try another criterion="friedman_mse"
regressior_model3 = DecisionTreeRegressor(criterion="friedman_mse",)
regressior_model3.fit(xtrain,ytrain)
print("Accuracy: ", round(regressior_model3.score(X=xtest,y=ytest),ndigits=3)*100,"%")

Accuracy:  93.89999999999999 %


In [12]:
pred = regressior_model3.predict(xtest)
pred

array([121.  ,  43.  ,  46.  , ...,  72.  ,  55.  ,  80.99])

In [13]:
ytest

2789    123.00
4838     43.50
3533     46.50
192      70.65
7034     77.90
         ...  
1256     32.00
4524     77.00
5167     72.00
3040     54.00
2853     83.09
Name: price, Length: 2136, dtype: float64

In [14]:
predict_one = xtest.iloc[500,:].values
predict_one

array([2.000000e+00, 1.000000e+00, 1.280000e+03, 2.000000e+00,
       5.859375e+03, 1.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 1.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
       0.000000e+00, 0.000000e+00, 0.000000e+00, 0.0000

In [15]:
regressior_model3.predict([predict_one])

array([75.])

In [16]:
ytest.iloc[500]

75.0

## Apply k-fold **cross_validition**

In [17]:
# if we want apply cross-validition then we have to use feature & level
cvs = cross_val_score(estimator=regressior_model3,X=features,y=level,cv=10)
cvs

array([0.99535796, 0.99241548, 0.78733933, 0.97108771, 0.97764326,
       0.98031212, 0.98601279, 0.8529541 , 0.64527578, 0.98604377])

### Maximum & Minimum **Accuracy**

In [18]:
cvs.max(),cvs.min()

(0.9953579558174739, 0.6452757813980174)

In [19]:
# Average Accuracy
cvs.mean()

0.9174442297238603

In [20]:
cvs.std()

0.11256759148809733

In [21]:
np.sqrt(cvs)

array([0.99767628, 0.99620052, 0.88732143, 0.98543783, 0.98875844,
       0.99010713, 0.99298177, 0.92355514, 0.8032906 , 0.99299737])

## Check **mean_squared_error**

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
mse = mean_squared_error(y_true=ytest,y_pred=pred)
mse

799.69670252809

In [24]:
np.sqrt(mse)

28.27890914671374

In [25]:
#sorted(sklearn.metrics.SCORERS.keys())
from sklearn.metrics import SCORERS

In [26]:
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])