In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn import datasets

In [2]:
Data = datasets.load_diabetes()

In [3]:
Data.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

In [4]:
Data_x = Data.data

In [5]:
Data_x

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [6]:
xtrain = Data_x[:-60]
xtest = Data_x[-60:]
ytrain = Data.target[:-60]
ytest = Data.target[-60:]

In [7]:
reg_obj = LinearRegression()

In [8]:
reg_obj.fit(xtrain,ytrain)

LinearRegression()

In [9]:
reg_obj.score(xtest,ytest)

0.6411935596287959

In [10]:
y_predicted = reg_obj.predict(xtest)

In [11]:
y_predicted

array([248.81417885, 116.47229602, 112.5135856 , 139.60639468,
       111.70597568,  91.17102468, 161.81030651,  76.1412881 ,
       254.81419366,  54.80818622, 101.75851324, 100.59019171,
       256.67441231, 167.30562088,  61.77412787, 184.98443933,
       170.13377069, 190.32792502, 182.67872698,  92.01231549,
       153.11287264, 251.27810366, 196.64739056, 279.62367372,
        48.48299973, 175.03412681, 203.07729915, 170.7936047 ,
       156.54321118, 151.82882454, 234.7521332 , 122.67117923,
       166.81370967, 172.9178181 , 223.71551788, 150.99518137,
       101.26182983,  82.77241294, 143.17212927, 192.0738332 ,
       195.86624056, 150.71190353, 173.21697668, 111.54954063,
       165.44195363, 131.75310718, 260.55756285,  99.97441968,
       116.83738098, 124.52651586, 221.5909535 ,  61.82955224,
       133.47463972, 119.65970834,  52.75278695, 192.87157152,
       106.25323253, 123.84767557, 208.6816387 ,  55.2380728 ])

In [12]:
print("mean squared error is: ",mean_squared_error(ytest,y_predicted))

mean squared error is:  2124.1983134829725


In [13]:
reg_obj.coef_

array([  13.89171113, -229.15391292,  512.03333698,  290.23970355,
       -739.02159288,  444.68124418,   71.1393508 ,  148.71677282,
        726.60045882,  104.44635315])

In [14]:
reg_obj.intercept_

152.43733203248547