In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score

In [3]:
df = pd.read_csv("/content/drive/My Drive/DataSets/bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

In [4]:
df.shape

(7120, 108)

## Split the features and level

In [5]:
features = df.drop(labels=["price"],axis="columns")
level = df["price"]

In [7]:
print(features.shape)
print(level.shape)

(7120, 107)
(7120,)


In [8]:
xtrain,xtest,ytrain,ytest = train_test_split(features,level,test_size=0.2,random_state=2023)

In [9]:
print('Shape of X_train = ', xtrain.shape)
print('Shape of y_train = ', ytrain.shape)
print('Shape of X_test = ', xtest.shape)
print('Shape of y_test = ', ytest.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


### Create the model

In [10]:
rfr = RandomForestRegressor(n_estimators=200,criterion="mse")

In [11]:
rfr.fit(xtrain,ytrain)
rfr.score(X=xtest,y=ytest)

0.8384070489663225

In [12]:
rfr2 = RandomForestRegressor(n_estimators=400,criterion="mse")
rfr2.fit(xtrain,ytrain)
rfr2.score(X=xtest,y=ytest)

0.8433566444110817

## Apply k-fold cross_validtion

In [13]:
cvs = cross_val_score(estimator=rfr2,X=features,y=level,cv=10)
cvs

array([0.96117686, 0.99793695, 0.84701342, 0.98420756, 0.99560118,
       0.95810116, 0.98920289, 0.97815117, 0.67088375, 0.98384984])

## To see max and min accuracy

In [14]:
cvs.max(),cvs.min()

(0.997936953365595, 0.6708837524268403)

In [15]:
# See average accuracy
cvs.mean()

0.9366124787942562

In [17]:
y_pred = rfr2.predict(X=xtest)
y_pred

array([ 94.69845,  78.16345,  42.037  , ..., 106.675  , 104.9425 ,
        71.8525 ])

In [18]:
ytest

706      94.55
5939     78.00
6416     42.00
2943     46.50
3985     49.50
         ...  
3583     58.00
737      67.00
2355    105.00
4225    105.00
1371     72.00
Name: price, Length: 1424, dtype: float64

In [20]:
predict_one = xtest.iloc[550,:].values
predict_one

array([2.00000000e+00, 1.00000000e+00, 9.00000000e+02, 2.00000000e+00,
       1.05555556e+04, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
      

In [21]:
rfr2.predict([predict_one])

array([94.89375])

In [23]:
ytest.iloc[550]

95.0