In [1]:
import numpy as np

## What are ufuncs?

ufuncs stands for "Universal Functions" and they are NumPy functions that operates on the ndarray object.

## Why use ufuncs?

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where boolean array or condition defining where the operations should take place.

dtype defining the return type of elements.

out output array where the return value should be copied.

## What is Vectorization?

Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

Add the Elements of Two Lists
list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements.

## Create Your Own ufunc

To create you own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

The frompyfunc() method takes the following arguments:

function - the name of the function.

inputs - the number of input arguments (arrays).

outputs - the number of output arrays.

In [2]:
def myadd(x, y):
    return x + y

myadd = np.frompyfunc(myadd, 2, 1)

In [3]:
myadd(4, 5)

9

In [4]:
myadd([1,2,3,4], [5,6,7,8])

array([6, 8, 10, 12], dtype=object)

In [5]:
# Check if a function is a ufunc

print(type(np.add))

<class 'numpy.ufunc'>


In [6]:
# If it is not a ufunc, it will return another type,
# like this built-in NumPy function for joining two or more arrays

print(type(np.concatenate))

<class 'function'>


# Simple Arithmetic

## add()

In [7]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

newarr

array([30, 32, 34, 36, 38, 40])

In [8]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])

print(np.add(arr1, arr2))

[[ 2  4  6]
 [ 8 10 12]]


## NumPy Summations

What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [9]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

newarr

12

In [10]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=0)

newarr

array([2, 4, 6])

### Summation Over an Axis

If you specify axis=1, NumPy will sum the numbers in each array.

In [11]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

newarr

array([6, 6])

## Cummulative Sum

Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

Perfom partial sum with the cumsum() function.

In [12]:
arr = np.array([1, 2, 3, 4, 5])

newarr = np.cumsum(arr)

newarr

array([ 1,  3,  6, 10, 15])

In [13]:
arr = np.array([[1,2,3],[4,5,6]])

newarr = np.cumsum(arr)

newarr

array([ 1,  3,  6, 10, 15, 21])

## Subtraction()

In [14]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

newarr

array([-10, -10, -10, -10, -10, -10])

In [15]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])

print(np.subtract(arr1, arr2))

[[0 0 0]
 [0 0 0]]


## Multiplication()

In [16]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

newarr

array([200, 231, 264, 299, 336, 375])

In [17]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])

print(np.multiply(arr1, arr2))

[[ 1  4  9]
 [16 25 36]]


## NumPy Products

To find the product of the elements in an array, use the prod() function.

In [18]:
arr = np.array([1,2,3,4]) # 1 x 2 x 3 x 4 = 24

result = np.prod(arr)

result

24

In [19]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.prod([arr1, arr2])

print(x)

# 40320 because 1*2*3*4*5*6*7*8 = 40320

40320


In [20]:
arr = np.array([[1,2,3], [4,5,6]])

np.prod(arr)

# 1*2*3*4*5*6 = 720

720

In [21]:
# Using product() function

arr = np.array([[1,2,3], [4,5,6]])

np.product(arr)

720

In [22]:
# Using product() function

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

x = np.product([arr1, arr2])

print(x)

40320


### Product Over an Axis

If you specify axis=1, NumPy will return the product of each array.

In [23]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=1)

print(newarr)

[  24 1680]


In [24]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

newarr = np.prod([arr1, arr2], axis=0)

print(newarr)

[ 5 12 21 32]


## Cummulative Product

Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

Perfom partial sum with the cumprod() function.

In [25]:
arr = np.array([5, 6, 7, 8])

newarr = np.cumprod(arr)

print(newarr)

[   5   30  210 1680]


In [26]:
# Using cumproduct() function

arr = np.array([5, 6, 7, 8])

newarr = np.cumproduct(arr)

print(newarr)

[   5   30  210 1680]


## Division()

In [27]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.divide(arr1, arr2)

newarr

array([0.5       , 0.52380952, 0.54545455, 0.56521739, 0.58333333,
       0.6       ])

In [28]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])

print(np.divide(arr1, arr2))

[[1. 1. 1.]
 [1. 1. 1.]]


## Power()

In [29]:
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([2, 2, 3, 3, 4, 5])

newarr = np.power(arr1, arr2)

newarr

array([   100,    121,   1728,   2197,  38416, 759375])

In [30]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[1,2,3],[4,5,6]])

print(np.power(arr1, arr2))

[[    1     4    27]
 [  256  3125 46656]]


## Remainder

In [31]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


In [32]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[ 1  6  3  0  0 27]


## Quotient and Mod

The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [33]:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


## Absolute Values

Both the absolute() and the abs() functions functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [34]:
arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


## Rounding Decimals

There are primarily five ways of rounding off decimals in NumPy:

1) truncation

2) fix

3) rounding

4) floor

5) ceil

### Truncation

Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [35]:
arr = np.trunc([-3.1666, 3.6667])

arr

array([-3.,  3.])

In [36]:
arr = np.fix([-3.1666, 3.6667])

arr

array([-3.,  3.])

### Rounding

The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2

In [37]:
arr = np.round(3.1666, 2)

arr

3.17

### Floor

The floor() function rounds off decimal to nearest lower integer.

E.g. floor of 3.166 is 3.

In [38]:
arr = np.floor([-3.1666, 3.6667])

arr

array([-4.,  3.])

### Ceil

The ceil() function rounds off decimal to nearest upper integer.

E.g. ceil of 3.166 is 43

In [39]:
arr = np.ceil([-3.1666, 3.6667])

arr

array([-3.,  4.])

## NumPy Logs

NumPy provides functions to perform log at the base 2, e and 10.

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place -inf or inf in the elements if the log can not be computed.



### Log at Base 2

Use the log2() function to perform log at the base 2.

In [40]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.log2(arr)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  ])

### Log at Base 10

Use the log10() function to perform log at the base 10.

In [42]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251])

### Natural Log, or Log at Base e

Use the log() function to perform log at the base e.

In [44]:
arr = np.arange(1, 10)

np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Log at Any Base

NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter

In [45]:
import math

In [46]:
nplog = np.frompyfunc(math.log, 2, 1)

nplog(100, 15)

1.7005483074552052

## NumPy Differences


A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [47]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr)

print(newarr)

[  5  10 -20]


We can perform this operation repeatedly by giving parameter n.

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]

In [48]:
arr = np.array([10, 15, 25, 5])

newarr = np.diff(arr, n=2)

print(newarr)

# [5 -30] because: 15-10=5, 25-15=10, and 5-25=-20 AND 10-5=5 and -20-10 = -30

[  5 -30]


## NumPy LCM Lowest Common Multiple

The Lowest Common Multiple is the least number that is common multiple of both of the numbers.

In [49]:
x = np.lcm(4, 6)

print(x)

12


### Finding LCM in Arrays

To find the Lowest Common Multiple of all values in an array, you can use the reduce() method.

The reduce() method will use the ufunc, in this case the lcm() function, on each element, and reduce the array by one dimension

In [50]:
arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


In [51]:
np.lcm.reduce([3, 12, 20])

60

## NumPy GCD Greatest Common Denominator


The GCD (Greatest Common Denominator), also known as HCF (Highest Common Factor) is the biggest number that is a common factor of both of the numbers.

In [52]:
np.gcd(6, 9)

# 3 because that is the highest number both numbers can be divided by (6/3=2 and 9/3=3)

3

### Finding GCD in Arrays

To find the Highest Common Factor of all values in an array, you can use the reduce() method.

The reduce() method will use the ufunc, in this case the gcd() function, on each element, and reduce the array by one dimension.

In [53]:
arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

# Returns: 4 because that is the highest number all values can be divided by.

4


## Trigonometric Functions

NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [54]:
x = np.sin(np.pi/2)

print(x)

1.0


In [55]:
# Find sine values for all of the values in arr

arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.sin(arr)

print(x)

[1.         0.8660254  0.70710678 0.58778525]


### Convert Degrees Into Radians

By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

Note: radians values are pi/180 * degree_values.

In [56]:
arr = np.array([90, 180, 270, 360])

x = np.deg2rad(arr)

print(x)

[1.57079633 3.14159265 4.71238898 6.28318531]


### Radians to Degrees

In [57]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


## Finding Angles

Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [58]:
x = np.arcsin(1.0)

print(x)

1.5707963267948966


In [59]:
# Angles of Each Value in Arrays

# Find the angle for all of the sine values in the array

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


## Hypotenues

Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [60]:
base = 3
perp = 4

x = np.hypot(base, perp)

print(x)

5.0


## Hyperbolic Functions

NumPy provides the ufuncs sinh(), cosh() and tanh() that take values in radians and produce the corresponding sinh, cosh and tanh values..

In [61]:
x = np.sinh(np.pi/2)

print(x)

2.3012989023072947


In [62]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])

x = np.cosh(arr)

print(x)

[2.50917848 1.60028686 1.32460909 1.20397209]


## Finding Angles

Finding angles from values of hyperbolic sine, cos, tan. E.g. sinh, cosh and tanh inverse (arcsinh, arccosh, arctanh).

Numpy provides ufuncs arcsinh(), arccosh() and arctanh() that produce radian values for corresponding sinh, cosh and tanh values given.

In [63]:
x = np.arcsinh(1.0)

print(x)

0.881373587019543


In [64]:
# Find the angle for all of the tanh values in array

arr = np.array([0.1, 0.2, 0.5])

x = np.arctanh(arr)

print(x)

[0.10033535 0.20273255 0.54930614]


## NumPy Set Operations

What is a Set

A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

Create Sets in NumPy

We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays

In [65]:
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])

x = np.unique(arr)

x

array([1, 2, 3, 4, 5, 6, 7])

#### Finding Union

To find the unique values of two arrays, use the union1d() method.

In [66]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

newarr

array([1, 2, 3, 4, 5, 6])

#### Finding Intersection

To find only the values that are present in both arrays, use the intersect1d() method.

In [67]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

newarr

# Note: the intersect1d() method takes an optional argument assume_unique, which if set to True can speed up computation.
#       It should always be set to True when dealing with sets.

array([3, 4])

#### Finding Difference

To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

In [68]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

newarr

# Note: the setdiff1d() method takes an optional argument assume_unique, which if set to True can speed up computation. 
#       It should always be set to True when dealing with sets.

array([1, 2])

#### Finding Symmetric Difference

To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [69]:
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

newarr

# Note: the setxor1d() method takes an optional argument assume_unique, which if set to True can speed up computation. 
#       It should always be set to True when dealing with sets.

array([1, 2, 5, 6])