In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [3]:
Data = load_breast_cancer()
df = pd.DataFrame(data=np.c_[Data.data,Data.target],columns=[list(Data.feature_names)+["target"]])
df.head()

mean radius mean texture  ... worst fractal dimension target
0       17.99        10.38  ...                 0.11890    0.0
1       20.57        17.77  ...                 0.08902    0.0
2       19.69        21.25  ...                 0.08758    0.0
3       11.42        20.38  ...                 0.17300    0.0
4       20.29        14.34  ...                 0.07678    0.0

[5 rows x 31 columns]

In [4]:
df.shape

(569, 31)

## Split the features and level

In [5]:
features = df.iloc[:,0:-1]
level = df.iloc[:,-1]

In [6]:
xtrain,xtest,ytrain,ytest = train_test_split(features,level,test_size=0.2,random_state=2031)

In [7]:
print("Shape of xtrain: ",xtrain.shape)
print("Shape of ytrain: ",ytrain.shape)
print("Shape of xtest: ",xtest.shape)
print("Shape of ytest: ",ytest.shape)

Shape of xtrain:  (455, 30)
Shape of ytrain:  (455,)
Shape of xtest:  (114, 30)
Shape of ytest:  (114,)


## Create Model

In [8]:
# n_estimators means number of decision create by algorithm. you can change value if you want 
# to create more than 100 tree ex: n_estimators=200 as your wish
rfc = RandomForestClassifier(n_estimators=100,criterion="gini") 

In [9]:
rfc.fit(X=xtrain,y=ytrain)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

## Accuracy

In [10]:
rfc.score(X=xtest,y=ytest)

0.9649122807017544

In [12]:
pred = rfc.predict(xtest)
pred

array([0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1.,
       0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 0., 1., 1.,
       1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1.,
       0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0.])

In [17]:
predict_one = xtest.iloc[75,:].values
predict_one

array([9.742e+00, 1.567e+01, 6.150e+01, 2.899e+02, 9.037e-02, 4.689e-02,
       1.103e-02, 1.407e-02, 2.081e-01, 6.312e-02, 2.684e-01, 1.409e+00,
       1.750e+00, 1.639e+01, 1.380e-02, 1.067e-02, 8.347e-03, 9.472e-03,
       1.798e-02, 4.261e-03, 1.075e+01, 2.088e+01, 6.809e+01, 3.552e+02,
       1.467e-01, 9.370e-02, 4.043e-02, 5.159e-02, 2.841e-01, 8.175e-02])

In [18]:
rfc.predict([predict_one])

array([1.])

In [19]:
Data.target_names

array(['malignant', 'benign'], dtype='<U9')