In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [2]:
d = load_breast_cancer()
df = pd.DataFrame(data=np.c_[d.data,d.target],columns=[list(d.feature_names)+["target"]])
df

mean radius mean texture  ... worst fractal dimension target
0         17.99        10.38  ...                 0.11890    0.0
1         20.57        17.77  ...                 0.08902    0.0
2         19.69        21.25  ...                 0.08758    0.0
3         11.42        20.38  ...                 0.17300    0.0
4         20.29        14.34  ...                 0.07678    0.0
..          ...          ...  ...                     ...    ...
564       21.56        22.39  ...                 0.07115    0.0
565       20.13        28.25  ...                 0.06637    0.0
566       16.60        28.08  ...                 0.07820    0.0
567       20.60        29.33  ...                 0.12400    0.0
568        7.76        24.54  ...                 0.07039    1.0

[569 rows x 31 columns]

In [3]:
df.shape

(569, 31)

# Split data

In [4]:
features = df.iloc[:,0:-1]
level = df.iloc[:,-1]

In [5]:
features.shape

(569, 30)

In [6]:
xtrain,xtest,ytrain,ytest = train_test_split(features,level,test_size=0.2,random_state=2020)

In [7]:
print('Shape of X_train = ', xtrain.shape)
print('Shape of y_train = ', ytrain.shape)
print('Shape of X_test = ', xtest.shape)
print('Shape of y_test = ', ytest.shape)

Shape of X_train =  (455, 30)
Shape of y_train =  (455,)
Shape of X_test =  (114, 30)
Shape of y_test =  (114,)


# Before features scaling
## Create Model

In [8]:
svm_rbf = SVC(kernel="rbf")
svm_rbf.fit(xtrain,ytrain)
svm_rbf.score(xtest,ytest)

0.9122807017543859

# Apply features scaling

In [9]:
sc = StandardScaler()

In [10]:
x_train = sc.fit_transform(xtrain)
x_test = sc.transform(xtest)

In [11]:
svm_rbf_sc = SVC(kernel="rbf")
svm_rbf_sc.fit(x_train,ytrain)
svm_rbf_sc.score(x_test,ytest)

0.956140350877193

In [12]:
# Apply different kernel
svm_poly_sc = SVC(kernel="poly")
svm_poly_sc.fit(x_train,ytrain)
svm_poly_sc.score(x_test,ytest)

0.9210526315789473

In [13]:
# Apply different kernel
svm_linear_sc = SVC(kernel="linear")
svm_linear_sc.fit(x_train,ytrain)
svm_linear_sc.score(x_test,ytest)

0.9649122807017544

In [14]:
y_predict = svm_linear_sc.predict(X=xtest)
y_predict

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
pred_one = xtest.iloc[71,:].values
pred_one

array([1.149e+01, 1.459e+01, 7.399e+01, 4.049e+02, 1.046e-01, 8.228e-02,
       5.308e-02, 1.969e-02, 1.779e-01, 6.574e-02, 2.034e-01, 1.166e+00,
       1.567e+00, 1.434e+01, 4.957e-03, 2.114e-02, 4.156e-02, 8.038e-03,
       1.843e-02, 3.614e-03, 1.240e+01, 2.190e+01, 8.204e+01, 4.676e+02,
       1.352e-01, 2.010e-01, 2.596e-01, 7.431e-02, 2.941e-01, 9.180e-02])

In [17]:
svm_linear_sc.predict([pred_one])

array([0.])

In [19]:
ytest.iloc[0]

0.0