In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [3]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# different data types

arr = np.array([1,3,5,5.5,63.58,True])

arr

array([ 1.  ,  3.  ,  5.  ,  5.5 , 63.58,  1.  ])

In [6]:
arr = np.array([1,2,3,4,5], dtype=np.float32)

arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [7]:
a = np.array(42)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# check the dimensions

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
# Higher Dimensional Arrays

arr = np.array([1,2,3,4,5], ndmin=5)

print(arr)

[[[[[1 2 3 4 5]]]]]


In [9]:
print(arr.ndim)

5


## Reverse the array

In [10]:
arr = np.array([100,230,400,500,700])

arr[::-1]

array([700, 500, 400, 230, 100])

## NumPy Array Indexing

1-d syntex-> array[start,stop,step] or array[index_num]

2-d syntex-> array[row,column] or array[row,column(start,stop,step])

### For 1-D array

In [11]:
arr = np.array([100,200,300,400,500])

In [12]:
arr[0]

100

In [13]:
arr[3]

400

In [14]:
arr[-1]

500

In [15]:
arr[-2]

400

### For 2-D array

In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

arr[0][0]

1

In [17]:
arr[0, 0]

1

In [18]:
arr[0, 4]

5

In [19]:
arr[1,2]

8

In [20]:
# Negative indexing

arr[1, -1]

10

### For 3-D array

In [21]:
arr = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])

print(arr[0, 1, 2])

6


In [22]:
arr[0][0][2]

3

In [23]:
arr[1, 0, -1]

9

In [24]:
arr[1, 1, -1]

12

In [25]:
arr[1][1][-1]

12

In [26]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
# Reverse 3-d array

arr2 = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])

arr2[::-1]

array([[[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])

# Array Slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

### For 1-D array

In [28]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a[0:5])

print(a[:8])

print(a[5:])

print(a[: : 2])

print(a[-5:-1])

print(a[-6:])

print(a[-6:-1:2])

print(a[-6::2])

[1 2 3 4 5]
[1 2 3 4 5 6 7 8]
[ 6  7  8  9 10]
[1 3 5 7 9]
[6 7 8 9]
[ 5  6  7  8  9 10]
[5 7 9]
[5 7 9]


### For 2-D array

In [29]:
b = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(b[0, 1:])

print(b[0, :3])

print(b[0, 1:4])

print(b[1, 1:])

print(b[1, :3])

[2 3 4 5]
[1 2 3]
[2 3 4]
[ 7  8  9 10]
[6 7 8]


In [30]:
b[0, ::2]

array([1, 3, 5])

In [31]:
b[1, -5:-1]

array([6, 7, 8, 9])

In [32]:
b[1, -5:]

array([ 6,  7,  8,  9, 10])

In [33]:
b[1, -5::2]

array([ 6,  8, 10])

In [34]:
b[0:2, 2]

array([3, 8])

In [35]:
b[::, 0:4]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [36]:
b[::, ::2]

array([[ 1,  3,  5],
       [ 6,  8, 10]])

### For 3-D array

In [37]:
arr6 = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])


arr6[0, 0, 0:]

array([1, 2, 3])

In [38]:
arr6[0, 0, 1:]

array([2, 3])

In [39]:
arr6[0, 0:, 0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
arr6[1, 1, -3::]

array([10, 11, 12])

## Advance Indexing and Slicing

### For 1-D array

In [41]:
# syntex-> array([[row][col]])

arr3 = np.array([1,2,3,4,5,6,7,8,9,10])

# using array
index = np.array([2,4,6])

print(arr3[index])

[3 5 7]


In [42]:
# Using list

print(arr3[[1,5,8,9]])

[ 2  6  9 10]


### For 2-D array

In [43]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr4[[0,2],[2,0]])

print()

print(arr4[[1,1,2],[0,2,1]])

print()

print(arr4[arr4>3])

[3 7]

[4 6 8]

[4 5 6 7 8 9]


In [44]:
arr6 = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]],dtype=float)
print(arr6)

print()

print(arr6.dtype)

print()

print(arr6[:2, ::2])

[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]

float64

[[-1.  0.]
 [ 4.  6.]]


### For 3-D array

In [45]:
arr5 = np.array([[
    [10,20,30],
    [40,50,60],
    [70,80,90]]])

print(arr5[[0],[0,0,1,2],[1,2,2,2]])

print()

print(arr5[[0],[0,1,2],[0,1,2]])

print()

print(arr5[arr5>40])

[20 30 60 90]

[10 50 90]

[50 60 70 80 90]


## Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [46]:
arr7 = np.array((1,2,3))

# Check the data type of numpy array
arr7.dtype

dtype('int32')

In [47]:
arr8 = np.array(['apple', 'banana', 'cherry'])

arr8.dtype

dtype('<U6')

In [48]:
# Creating Arrays With a Defined Data Type

arr9 = np.array((10,20,30), dtype='S')

print(arr9)

print(arr9.dtype)

[b'10' b'20' b'30']
|S2


In [49]:
# For i, u, f, S and U we can define size as well.

# Create an array with data type 4 bytes integer:


arr10 = np.array([1, 2, 3, 4], dtype='i4')

print(arr10)
print(arr10.dtype)


[1 2 3 4]
int32


In [50]:
arr11 = np.array([10,2,3], dtype=np.int64)

arr11.dtype

dtype('int64')

## Converting Data Type on Existing Arrays

In [51]:
arr12 = np.array([1.1, 2.1, 3.1])

newarr = arr12.astype('i')

print(newarr)

print(newarr.dtype)

[1 2 3]
int32


In [52]:
arr13 = np.array([1.1, 2.1, 3.1])

newarr2 = arr13.astype(int)

print(newarr2)
print(newarr2.dtype)

[1 2 3]
int32


In [53]:
arr14 = np.array([1, 0, 3])

newarr3 = arr14.astype(bool)

print(newarr3)
print(newarr3.dtype)

[ True False  True]
bool


## NumPy Array Copy vs View

The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

### Copy

In [54]:
# Make a copy, change the original array, and display both arrays:


arr15 = np.array([1, 2, 3, 4, 5])

x = arr15.copy()

arr15[0] = 42

print(arr15)

print(x)

[42  2  3  4  5]
[1 2 3 4 5]


### View

In [55]:
arr16 = np.array([1, 2, 3, 4, 5])

y = arr16.view()

arr16[0] = 42 # change the first value of original array

print(arr16)

print(y)

[42  2  3  4  5]
[42  2  3  4  5]


In [56]:
# change the view

y[0] = 100

print(arr16)

print(y)

[100   2   3   4   5]
[100   2   3   4   5]


# numpy array shape

In [57]:
arr17 = np.array((13,10,25))

arr18 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

arr19 = np.array([ [[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]] ])
                 
print(arr17.shape)
print(arr18.shape)
print(arr19.shape)

(3,)
(2, 4)
(2, 2, 3)


# NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

### Reshape From 1-D to 2-D

In [58]:
# The outermost dimension will have 4 arrays, each with 3 elements:

arr20 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr4 = arr20.reshape(4, 3)

print(newarr4)

print()

print(newarr4.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

(4, 3)


### Reshape From 1-D to 3-D

Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [59]:
arr21 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr5 = arr21.reshape(2, 3, 2)

print(newarr5)

print()

print(newarr5.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]

(2, 3, 2)


### Unknown Dimension

You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [60]:
# Convert 1D array with 8 elements to 3D array with 2x2 elements:



arr22 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr6 = arr22.reshape(2, 2, -1)

print(newarr6)

print()

print(newarr6.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

(2, 2, 2)


## Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this

In [61]:
arr23 = np.array([[1, 2, 3], [4, 5, 6]])

newarr7 = arr23.reshape(-1)

print(newarr7)

[1 2 3 4 5 6]


# NumPy Array Iterating

In [62]:
myarr = np.array([1,2,3,20,35])

for i in myarr:
    print(i)

1
2
3
20
35


In [63]:
myarr2 = np.array([[1, 2, 3], [4, 5, 6]])

for i in myarr2:
    print(i)

[1 2 3]
[4 5 6]


In [64]:
for i in myarr2:
    for j in i:
        print(j)

1
2
3
4
5
6


In [65]:
myarr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in myarr3:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Arrays Using nditer()

The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

Iterating on Each Scalar Element

In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [66]:
myarr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for i in np.nditer(myarr4):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating Array With Different Data Types

We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [67]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


### Iterating With Different Step Size

In [68]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x)

1
3
5
7


### Enumerated Iteration Using ndenumerate()

Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [69]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
      print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [70]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
      print(idx, x)


(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


## NumPy Joining Array

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

### For 1-D array

In [71]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

result = np.concatenate((arr1, arr2))

result

array([1, 2, 3, 4, 5, 6])

### For 2-D array

In [72]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

arr

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [73]:
result2 = np.concatenate((arr1, arr2), axis=1)

result2

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# Joining Arrays Using Stack Functions

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

### For 1-D array

In [74]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [75]:
arr2 = np.stack((arr1, arr2), axis=1)

arr2

array([[1, 4],
       [2, 5],
       [3, 6]])

## Stacking Along Rows

In [76]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


## Stacking Along Columns

In [77]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


## Stacking Along Height (depth)

In [78]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# NumPy Splitting Array

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

### For 1-D array

In [79]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [80]:
newarr[0]

array([1, 2])

In [81]:
newarr[0][0]

1

In [82]:
# If the array has less elements than required, it will adjust from the end accordingly.

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


### For 2-D array

In [83]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [84]:
newarr[0]

array([[1, 2],
       [3, 4]])

In [85]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [86]:
newarr[1]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [87]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

# split along the row (axis=1)
newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Rows wise spliting

In [88]:
# Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.


arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


## Column wise spliting

In [89]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


## Stacking Along Height (depth)

In [94]:
x = np.arange(16.0).reshape(2, 2, 4)

x

array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.]],

       [[ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]]])

In [95]:
y = np.dsplit(x, 2)

y

[array([[[ 0.,  1.],
         [ 4.,  5.]],
 
        [[ 8.,  9.],
         [12., 13.]]]),
 array([[[ 2.,  3.],
         [ 6.,  7.]],
 
        [[10., 11.],
         [14., 15.]]])]

# NumPy Searching Arrays

In [96]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

# It will return the index number where the condition match
x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [97]:
# Find the indexes where the values are even

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


### Search Sorted

There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

The searchsorted() method is assumed to be used on sorted arrays.

In [101]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [102]:
# Search From the Right Side
# By default the left most index is returned, but we can give side='right' to return the right most index instead.

x = np.searchsorted(arr, 7, side="right")

x

2

In [103]:
# Multiple Values

# To search for more than one value, use an array with the specified values.


# Find the indexes where the values 2, 4, and 6 should be inserted


arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

# The return value is an array: [1 2 3] containing the three 
# indexes where 2, 4, 6 would be inserted in the original array to maintain the order.

[1 2 3]


# NumPy Sorting Arrays

Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [104]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [105]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [106]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [107]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# NumPy Filter Array

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

A boolean index list is a list of booleans corresponding to indexes in the array.

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [108]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [110]:
arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
    # if the element is higher than 42, set the value to True, otherwise False:
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, False, True, True]
[43 44]


In [111]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for i in arr:
    if i % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

newarr

array([2, 4, 6])

In [112]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)

print(newarr)

[False False  True  True]
[43 44]


In [113]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
