In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_in

In [3]:
arr = np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# different data types

arr = np.array([1,3,5,5.5,63.58,True])

arr

array([ 1.  ,  3.  ,  5.  ,  5.5 , 63.58,  1.  ])

In [6]:
arr = np.array([1,2,3,4,5], dtype=np.float32)

arr

array([1., 2., 3., 4., 5.], dtype=float32)

In [7]:
a = np.array(42)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# check the dimensions

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [8]:
# Higher Dimensional Arrays

arr = np.array([1,2,3,4,5], ndmin=5)

print(arr)

[[[[[1 2 3 4 5]]]]]


In [9]:
print(arr.ndim)

5


## Reverse the array

In [10]:
arr = np.array([100,230,400,500,700])

arr[::-1]

array([700, 500, 400, 230, 100])

## NumPy Array Indexing

### For 1-D array

In [11]:
arr = np.array([100,200,300,400,500])

In [12]:
arr[0]

100

In [13]:
arr[3]

400

In [14]:
arr[-1]

500

In [15]:
arr[-2]

400

### For 2-D array

In [16]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

arr[0][0]

1

In [17]:
arr[0, 0]

1

In [18]:
arr[0, 4]

5

In [19]:
arr[1,2]

8

In [20]:
# Negative indexing

arr[1, -1]

10

### For 3-D array

In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [22]:
arr[0][0][2]

3

In [23]:
arr[1, 0, -1]

9

In [24]:
arr[1, 1, -1]

12