In [1]:
import numpy as np

## For 1-D array

In [2]:
arr = np.array([1,2,3,4])

arr*3

array([ 3,  6,  9, 12])

In [4]:
arr + 10

array([11, 12, 13, 14])

In [7]:
arr / 2

array([0.5, 1. , 1.5, 2. ])

In [8]:
arr // 2

array([0, 1, 1, 2], dtype=int32)

In [5]:
arr ** 3

array([ 1,  8, 27, 64], dtype=int32)

In [6]:
arr * arr

array([ 1,  4,  9, 16])

In [9]:
arr + arr

array([2, 4, 6, 8])

In [10]:
arr + arr * arr

array([ 2,  6, 12, 20])

## For 2-D array

In [11]:
arr2 = np.array([[1,2,3], [4,5,6]])

In [12]:
arr2 * arr2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
arr2 + arr2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [14]:
arr2 / arr2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
arr2 ** arr2

array([[    1,     4,    27],
       [  256,  3125, 46656]])

In [16]:
arr2 + 100

array([[101, 102, 103],
       [104, 105, 106]])

In [17]:
arr2 + 100 - 30

array([[71, 72, 73],
       [74, 75, 76]])

In [18]:
(arr2 + 10) - (arr2 * 2)

array([[9, 8, 7],
       [6, 5, 4]])