In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.neighbors import KNeighborsRegressor

In [2]:
df = pd.read_csv("/content/drive/My Drive/DataSets/bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

In [3]:
df.shape

(7120, 108)

# Split the features and level

In [4]:
features = df.drop(labels=["price"],axis=1)
level = df["price"]

In [5]:
xtrain,xtest,ytrain,ytest = train_test_split(features,level,test_size=0.3,random_state=2020)

In [6]:
print('Shape of X_train = ', xtrain.shape)
print('Shape of y_train = ', ytrain.shape)
print('Shape of X_test = ', xtest.shape)
print('Shape of y_test = ', ytest.shape)

Shape of X_train =  (4984, 107)
Shape of y_train =  (4984,)
Shape of X_test =  (2136, 107)
Shape of y_test =  (2136,)


# Create Modle

In [7]:
knr = KNeighborsRegressor(n_neighbors=5)
knr.fit(xtrain,ytrain)

KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                    weights='uniform')

In [8]:
knr.score(X=xtest,y=ytest)

0.9236364680017282

In [9]:
knr2 = KNeighborsRegressor(n_neighbors=15)
knr2.fit(xtrain,ytrain)
knr2.score(X=xtest,y=ytest)

0.8899800102029323

In [10]:
knr.predict(X=xtest)

array([138.4 ,  75.  ,  64.9 , ...,  74.04, 153.  ,  65.  ])

In [11]:
ytest

1360    140.0
2975     75.0
1893     65.0
1761    132.0
3045     51.5
        ...  
5892     65.0
6808     75.0
2342     73.9
4962    155.0
4839     65.0
Name: price, Length: 2136, dtype: float64

# Apply cross_validtion

In [12]:
cvs = cross_val_score(estimator=knr,X=features,y=level,cv=10)
cvs

array([0.8283268 , 0.99181822, 0.79500443, 0.99195144, 0.9913482 ,
       0.99540153, 0.97453652, 0.98279454, 0.8509264 , 0.89537251])

In [13]:
# see max and min accuracy
cvs.max(),cvs.min()

(0.9954015291147923, 0.7950044291480761)

In [14]:
# average accuracy
cvs.mean()

0.9297480586454172

In [16]:
pred_one = xtest.iloc[1799,:].values
pred_one

array([3.0000000e+00, 2.0000000e+00, 1.6400000e+03, 3.0000000e+00,
       1.4695122e+04, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e

In [17]:
knr.predict(X=[pred_one])

array([241.])

In [18]:
ytest.iloc[1799]

241.0