In [1]:
import numpy as np

# From shape or value

### numpy.empty

numpy.empty(shape, dtype=float, order='C', *, like=None)

In [3]:
arr = np.empty(3,dtype=int)

print(arr)

arr[0] = 10
arr[1] = 20
arr[2] = 30

print(arr)

[1948282739  544498024 1663071337]
[10 20 30]


In [4]:
arr = np.empty([3,3], dtype=np.int32)
arr

array([[   0,    1,    0],
       [ 574, 1352,    0],
       [ 768,  229,    0]])

In [5]:
arr = np.empty([2,3,3], dtype=np.int32)
arr

array([[[  4128860,   6029375,   3801155],
        [  5570652,   6619251,   7536754],
        [  6357084,   6357100,   6881389]],

       [[  4259932,   7340144,   6357060],
        [  6357108,   4980828,   6488175],
        [  7077985, 147324928,     32763]]])

### numpy.empty_like

numpy.empty_like(prototype, dtype=None, order='K', subok=True, shape=None)

Return a new array with the same shape and type as a given array.

In [7]:
a = ([1,2,3], [4,5,6])  # a is array-like

a

([1, 2, 3], [4, 5, 6])

In [8]:
np.empty_like(a)

array([[   36252000,  1769276762,   241787360],
       [        574,           0, -2147483648]])

In [9]:
a = np.array([[1., 2., 3.],[4.,5.,6.]])

a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [10]:
a.dtype

dtype('float64')

In [11]:
np.empty_like(a)

array([[1., 2., 3.],
       [4., 5., 6.]])

### numpy.eye

numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)

Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [13]:
arr = np.eye(2)
arr

array([[1., 0.],
       [0., 1.]])

In [14]:
arr = np.eye(2,2)
arr

array([[1., 0.],
       [0., 1.]])

In [16]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr = np.eye(3, k=1)

In [18]:
arr

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

### numpy.identity

numpy.identity(n, dtype=None, *, like=None)

Return the identity array.

The identity array is a square array with ones on the main diagonal.

In [19]:
arr = np.identity(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])