In [1]:
import numpy as np

# Counting

### count_nonzero()

In [2]:
# numpy.count_nonzero(a, axis=None, *, keepdims=False)

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.count_nonzero(np.eye(4))

4

In [4]:
a = np.array([
    [0,1,7,0],
    [3,0,2,19]
])

np.count_nonzero(a)

5

In [5]:
np.count_nonzero(a, axis=0)

array([1, 1, 2, 1], dtype=int64)

In [6]:
np.count_nonzero(a, axis=1)

array([2, 3], dtype=int64)

In [7]:
np.count_nonzero(a, axis=1, keepdims=True)

array([[2],
       [3]], dtype=int64)

# Sorting

### sort()

In [8]:
a = np.array([[1,4],[3,1]])

np.sort(a) # sort along the last axis

array([[1, 4],
       [1, 3]])

In [9]:
np.sort(a, axis=None) # sort the flattened array

array([1, 1, 3, 4])

In [10]:
np.sort(a, axis=0) # sort along the first axis

array([[1, 1],
       [3, 4]])

In [11]:
np.sort(a, axis=1) # sort along the last axis

array([[1, 4],
       [1, 3]])

In [12]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]

values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)]

a = np.array(values, dtype=dtype)

In [13]:
a

array([(b'Arthur', 1.8, 41), (b'Lancelot', 1.9, 38),
       (b'Galahad', 1.7, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [14]:
np.sort(a, order='height')

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [15]:
np.sort(a, order=['age', 'height'])

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

### lexsort()

In [16]:
# numpy.lexsort(keys, axis=- 1)


a = [1,5,1,4,3,4,4] # First column

b = [9,4,0,4,0,2,1] # Second column

ind = np.lexsort((b,a)) # Sort by a, then by b

ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [17]:
[(a[i],b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

### argsort()

In [18]:
# numpy.argsort(a, axis=- 1, kind=None, order=None)

x = np.array([3,1,2])

np.argsort(x) # it returns the sort index

array([1, 2, 0], dtype=int64)

In [19]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [20]:
ind = np.argsort(x, axis=0)  # sorts along first axis (down)

ind

array([[0, 1],
       [1, 0]], dtype=int64)

In [21]:
ind = np.argsort(x, axis=1)  # sorts along last axis (across)

ind

array([[0, 1],
       [0, 1]], dtype=int64)

In [22]:
x = np.array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])

np.argsort(x, order=('x','y'))

array([1, 0], dtype=int64)

In [23]:
np.argsort(x, order=('y','x'))

array([0, 1], dtype=int64)

### ndarray.sort

In [24]:
# ndarray.sort(axis=- 1, kind=None, order=None)

a = np.array([[1,4], [3,1]])

a.sort(axis=1)

a

array([[1, 4],
       [1, 3]])

In [25]:
a.sort(axis=0)

a

array([[1, 3],
       [1, 4]])

In [26]:
a.sort()
a

array([[1, 3],
       [1, 4]])

### msort()

In [27]:
# numpy.msort(a)

a = np.array([5,1,0,4])

np.msort(a)

array([0, 1, 4, 5])