In [1]:
import numpy as np

# Counting

### count_nonzero()

In [2]:
# numpy.count_nonzero(a, axis=None, *, keepdims=False)

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [3]:
np.count_nonzero(np.eye(4))

4

In [4]:
a = np.array([
    [0,1,7,0],
    [3,0,2,19]
])

np.count_nonzero(a)

5

In [5]:
np.count_nonzero(a, axis=0)

array([1, 1, 2, 1], dtype=int64)

In [6]:
np.count_nonzero(a, axis=1)

array([2, 3], dtype=int64)

In [7]:
np.count_nonzero(a, axis=1, keepdims=True)

array([[2],
       [3]], dtype=int64)

# Sorting

### sort()

In [8]:
a = np.array([[1,4],[3,1]])

np.sort(a) # sort along the last axis

array([[1, 4],
       [1, 3]])

In [9]:
np.sort(a, axis=None) # sort the flattened array

array([1, 1, 3, 4])

In [10]:
np.sort(a, axis=0) # sort along the first axis

array([[1, 1],
       [3, 4]])

In [11]:
np.sort(a, axis=1) # sort along the last axis

array([[1, 4],
       [1, 3]])

In [12]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]

values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),('Galahad', 1.7, 38)]

a = np.array(values, dtype=dtype)

In [13]:
a

array([(b'Arthur', 1.8, 41), (b'Lancelot', 1.9, 38),
       (b'Galahad', 1.7, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [14]:
np.sort(a, order='height')

array([(b'Galahad', 1.7, 38), (b'Arthur', 1.8, 41),
       (b'Lancelot', 1.9, 38)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

In [15]:
np.sort(a, order=['age', 'height'])

array([(b'Galahad', 1.7, 38), (b'Lancelot', 1.9, 38),
       (b'Arthur', 1.8, 41)],
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i4')])

### lexsort()

In [16]:
# numpy.lexsort(keys, axis=- 1)


a = [1,5,1,4,3,4,4] # First column

b = [9,4,0,4,0,2,1] # Second column

ind = np.lexsort((b,a)) # Sort by a, then by b

ind

array([2, 0, 4, 6, 5, 3, 1], dtype=int64)

In [17]:
[(a[i],b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

### argsort()

In [18]:
# numpy.argsort(a, axis=- 1, kind=None, order=None)

x = np.array([3,1,2])

np.argsort(x) # it returns the sort index

array([1, 2, 0], dtype=int64)

In [19]:
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [20]:
ind = np.argsort(x, axis=0)  # sorts along first axis (down)

ind

array([[0, 1],
       [1, 0]], dtype=int64)

In [21]:
ind = np.argsort(x, axis=1)  # sorts along last axis (across)

ind

array([[0, 1],
       [0, 1]], dtype=int64)

In [22]:
x = np.array([(1, 0), (0, 1)], dtype=[('x', '<i4'), ('y', '<i4')])

np.argsort(x, order=('x','y'))

array([1, 0], dtype=int64)

In [23]:
np.argsort(x, order=('y','x'))

array([0, 1], dtype=int64)

### ndarray.sort

In [24]:
# ndarray.sort(axis=- 1, kind=None, order=None)

a = np.array([[1,4], [3,1]])

a.sort(axis=1)

a

array([[1, 4],
       [1, 3]])

In [25]:
a.sort(axis=0)

a

array([[1, 3],
       [1, 4]])

In [26]:
a.sort()
a

array([[1, 3],
       [1, 4]])

### msort()

In [27]:
# numpy.msort(a)

a = np.array([5,1,0,4])

np.msort(a)

array([0, 1, 4, 5])

# Searching

### numpy.argmax

numpy.argmax(a, axis=None, out=None, *, keepdims=(no value))

Returns the indices of the maximum values along an axis.

In [28]:
arr = np.array([1,5,9,1000,200,300,400])

np.argmax(arr)

# the maximum value exist in number 3 index that is 1000

3

In [29]:
arr = np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.argmax(arr)

8

In [31]:
np.argmax(arr, axis=0)

array([2, 2, 2], dtype=int64)

In [32]:
arr = np.array([[1, 2, 300],
                [4, 100, 6],
                [700, 8, 9]])

np.argmax(arr)

6

In [33]:
np.argmax(arr, axis=0)

array([2, 1, 0], dtype=int64)

In [37]:
arr = np.array([[1, 2000, 300],
                [4, 100, 600],
                [700, 8, 9]])

In [38]:
np.argmax(arr, axis=1)

array([1, 2, 0], dtype=int64)

In [39]:
np.argmax(arr, axis=1, keepdims=True)

array([[1],
       [2],
       [0]], dtype=int64)

### numpy.nanargmax

numpy.nanargmax(a, axis=None, out=None, *, keepdims=(no value))

Return the indices of the maximum values in the specified axis ignoring NaNs.

### numpy.argmin

numpy.argmin(a, axis=None, out=None, *, keepdims=(no value))

Returns the indices of the minimum values along an axis

In [40]:
arr = np.array([10,5,9,1000,200,300,400])

np.argmin(arr)

1

In [43]:
arr = np.array([[1, 2, 300],
                [4, 100, 6],
                [700, 1, 9]])

np.argmin(arr)

0

In [44]:
np.argmin(arr, axis=0)

array([0, 2, 1], dtype=int64)

In [48]:
arr = np.array([[1, 2, 300],
                [40, 10, 60],
                [7000, 1000, 900]])

In [49]:
np.argmin(arr, axis=1)

array([0, 1, 2], dtype=int64)

In [50]:
np.argmin(arr, axis=1, keepdims=True)

array([[0],
       [1],
       [2]], dtype=int64)

### numpy.nanargmin

numpy.nanargmin(a, axis=None, out=None, *, keepdims=(no value))

Return the indices of the minimum values in the specified axis ignoring NaNs.

### numpy.argwhere

numpy.argwhere(a)

Find the indices of array elements that are non-zero, grouped by element.

In [51]:
x = np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
np.argwhere(x>1)

# np.argwhere(a) is almost the same as np.transpose(np.nonzero(a)), 
# but produces a result of the correct shape for a 0D array.

# The output of argwhere is not suitable for indexing arrays. For this purpose use nonzero(a) instead.

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]], dtype=int64)

### numpy.nonzero

numpy.nonzero(a)

Return the indices of the elements that are non-zero.

### numpy.flatnonzero

numpy.flatnonzero(a)

Return indices that are non-zero in the flattened version of a.

### numpy.where

numpy.where(condition, [x, y, ]/)

Return elements chosen from x or y depending on condition.

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

### numpy.searchsorted

numpy.searchsorted(a, v, side='left', sorter=None)

Find indices where elements should be inserted to maintain order.

Find the indices into a sorted array a such that, if the corresponding elements in v were inserted before the indices, the order of a would be preserved.

In [55]:
np.searchsorted([1,2,3,4,5], 3)

2

In [56]:
np.searchsorted([1,2,3,4,5], 3, side='right')

3

In [57]:
np.searchsorted([1,2,3,4,5], [-10, 10, 2, 3])

array([0, 5, 1, 2], dtype=int64)

### numpy.extract

numpy.extract(condition, arr)

Return the elements of an array that satisfy some condition.

This is equivalent to np.compress(ravel(condition), ravel(arr)). If condition is boolean np.extract is equivalent to arr[condition].

In [58]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
condition = np.mod(arr, 3) == 0

condition

array([[ True, False, False,  True],
       [False, False,  True, False],
       [False,  True, False, False]])

In [60]:
np.extract(condition, arr)

array([0, 3, 6, 9])

In [61]:
arr[condition]

array([0, 3, 6, 9])