In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.datasets import load_breast_cancer
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB

In [6]:
data = load_breast_cancer()
df = pd.DataFrame(data=np.c_[data.data,data.target],columns=[list(data.feature_names)+["target"]])
df.head()

mean radius mean texture  ... worst fractal dimension target
0       17.99        10.38  ...                 0.11890    0.0
1       20.57        17.77  ...                 0.08902    0.0
2       19.69        21.25  ...                 0.08758    0.0
3       11.42        20.38  ...                 0.17300    0.0
4       20.29        14.34  ...                 0.07678    0.0

[5 rows x 31 columns]

In [7]:
df.shape

(569, 31)

In [8]:
features = df.iloc[:,0:-1]
level = df.iloc[:,-1]

In [9]:
xtrain,xtest,ytrain,ytest = train_test_split(features,level,test_size=0.2,random_state=8)

In [10]:
print('Shape of X_train = ', xtrain.shape)
print('Shape of y_train = ', ytrain.shape)
print('Shape of X_test = ', xtest.shape)
print('Shape of y_test = ', ytest.shape)

Shape of X_train =  (455, 30)
Shape of y_train =  (455,)
Shape of X_test =  (114, 30)
Shape of y_test =  (114,)


# apply GaussianNB

In [11]:
gaussianNb_model = GaussianNB()
gaussianNb_model.fit(xtrain,ytrain)
gaussianNb_model.score(X=xtest,y=ytest)

0.9473684210526315

# apply MultinomialNB

In [12]:
multinomialNb_model = MultinomialNB()
multinomialNb_model.fit(xtrain,ytrain)
multinomialNb_model.score(X=xtest,y=ytest)

0.8859649122807017

# apply BernoulliNB

In [13]:
bernoulliNb_model = BernoulliNB()
bernoulliNb_model.fit(xtrain,ytrain)
bernoulliNb_model.score(X=xtest,y=ytest)

0.5964912280701754

In [14]:
y_pred = gaussianNb_model.predict(X=xtest)

In [15]:
y_pred

array([1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 0.,
       1., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1.,
       1., 0., 0., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 0.,
       1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.])

# Apply k-fold cross_validtion

In [16]:
cvs = cross_val_score(estimator=gaussianNb_model,X=features,y=level,cv=10)
cvs

array([0.94736842, 0.87719298, 0.89473684, 0.92982456, 0.94736842,
       0.96491228, 0.92982456, 0.96491228, 0.94736842, 0.96428571])

In [17]:
# max and min accuracy
cvs.max(),cvs.min()

(0.9649122807017544, 0.8771929824561403)

In [18]:
# average accuracy
cvs.mean()

0.9367794486215537

In [19]:
pred_one = xtest.iloc[77,:].values
pred_one

array([1.234e+01, 2.222e+01, 7.985e+01, 4.645e+02, 1.012e-01, 1.015e-01,
       5.370e-02, 2.822e-02, 1.551e-01, 6.761e-02, 2.949e-01, 1.656e+00,
       1.955e+00, 2.155e+01, 1.134e-02, 3.175e-02, 3.125e-02, 1.135e-02,
       1.879e-02, 5.348e-03, 1.358e+01, 2.868e+01, 8.736e+01, 5.530e+02,
       1.452e-01, 2.338e-01, 1.688e-01, 8.194e-02, 2.268e-01, 9.082e-02])

In [20]:
gaussianNb_model.predict([pred_one])

array([1.])

In [21]:
ytest.iloc[77]

1.0

In [23]:
!install python 3.8

install: cannot stat 'python': No such file or directory
