In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split,KFold,cross_val_score
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import datasets

In [2]:
data = datasets.load_digits()

In [3]:
x_train,x_test,y_train,y_test = train_test_split(data.data,data.target,test_size=.3)

In [9]:
lr = LogisticRegression(max_iter=200)

In [10]:
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.9666666666666667

In [16]:
svc = SVC()

In [17]:
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.9888888888888889

In [18]:
rfc = RandomForestClassifier(n_estimators=100)

In [19]:
rfc.fit(x_train,y_train)
rfc.score(x_test,y_test)

0.9722222222222222

In [21]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [23]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


# We create a **function**

In [24]:
def get_score(model,x_train,x_test,y_train,y_test):
  model.fit(x_train,y_train)
  return model.score(x_test,y_test)

In [25]:
get_score(RandomForestClassifier(n_estimators=100),x_train,x_test,y_train,y_test)

0.9796296296296296

In [26]:
from sklearn.model_selection import StratifiedKFold

In [27]:
folds = StratifiedKFold(n_splits=3)

In [29]:
score_lr = []
score_svc = []
score_rfc = []
for train_index,test_index in kf.split(data.data):
  x_train,x_test,y_train,y_test = data.data[train_index],data.data[test_index],data.target[train_index],data.target[test_index]
  score_lr.append(get_score(LogisticRegression(max_iter=200),x_train,x_test,y_train,y_test))
  score_svc.append(get_score(SVC(),x_train,x_test,y_train,y_test))
  score_rfc.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


In [31]:
score_lr 

[0.9248747913188647, 0.9432387312186978, 0.9198664440734557]

In [32]:
score_svc

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [33]:
score_rfc

[0.9332220367278798, 0.9549248747913188, 0.9232053422370617]

In [34]:
cross_val_score(LogisticRegression(),data.data,data.target)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression


array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])

In [35]:
cross_val_score(SVC(),data.data,data.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [36]:
cross_val_score(RandomForestClassifier(),data.data,data.target)

array([0.92222222, 0.90555556, 0.95264624, 0.96935933, 0.92479109])