In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split,cross_val_score

In [3]:
data = load_breast_cancer()
df = pd.DataFrame(data=np.c_[data.data, data.target], columns=[list(data.feature_names)+['target']])
df

mean radius mean texture  ... worst fractal dimension target
0         17.99        10.38  ...                 0.11890    0.0
1         20.57        17.77  ...                 0.08902    0.0
2         19.69        21.25  ...                 0.08758    0.0
3         11.42        20.38  ...                 0.17300    0.0
4         20.29        14.34  ...                 0.07678    0.0
..          ...          ...  ...                     ...    ...
564       21.56        22.39  ...                 0.07115    0.0
565       20.13        28.25  ...                 0.06637    0.0
566       16.60        28.08  ...                 0.07820    0.0
567       20.60        29.33  ...                 0.12400    0.0
568        7.76        24.54  ...                 0.07039    1.0

[569 rows x 31 columns]

In [4]:
df.shape

(569, 31)

In [5]:
df.tail()

mean radius mean texture  ... worst fractal dimension target
564       21.56        22.39  ...                 0.07115    0.0
565       20.13        28.25  ...                 0.06637    0.0
566       16.60        28.08  ...                 0.07820    0.0
567       20.60        29.33  ...                 0.12400    0.0
568        7.76        24.54  ...                 0.07039    1.0

[5 rows x 31 columns]

## Split the features and level

In [6]:
features = df.iloc[:,:-1]
level = df.iloc[:,-1]

In [7]:
xtrain,xtest,ytrain,ytest = train_test_split(features,level,test_size=0.2,random_state=1)

In [8]:
print('Shape of X_train = ', xtrain.shape)
print('Shape of y_train = ', ytrain.shape)
print('Shape of X_test = ', xtest.shape)
print('Shape of y_test = ', ytest.shape)

Shape of X_train =  (455, 30)
Shape of y_train =  (455,)
Shape of X_test =  (114, 30)
Shape of y_test =  (114,)


# Create the model

In [9]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [10]:
knn.score(X=xtest,y=ytest)

0.9385964912280702

In [13]:
knn2 = KNeighborsClassifier(n_neighbors=10)
knn2.fit(xtrain,ytrain)
knn2.score(X=xtest,y=ytest)

0.9298245614035088

In [14]:
y_pred = knn.predict(X=xtest)
y_pred

array([0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 1.,
       1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
       1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 0., 1., 0., 1.,
       1., 0., 1., 0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 1., 1., 1., 1.])

In [15]:
pred_one = xtest.iloc[71,:].values
pred_one

array([1.278e+01, 1.649e+01, 8.137e+01, 5.025e+02, 9.831e-02, 5.234e-02,
       3.653e-02, 2.864e-02, 1.590e-01, 5.653e-02, 2.368e-01, 8.732e-01,
       1.471e+00, 1.833e+01, 7.962e-03, 5.612e-03, 1.585e-02, 8.662e-03,
       2.254e-02, 1.906e-03, 1.346e+01, 1.976e+01, 8.567e+01, 5.549e+02,
       1.296e-01, 7.061e-02, 1.039e-01, 5.882e-02, 2.383e-01, 6.410e-02])

In [16]:
knn.predict([pred_one])

array([1.])

In [17]:
ytest.iloc[71]

1.0

In [18]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

# Apply cross_validition

In [19]:
cvs = cross_val_score(estimator=knn,X=features,y=level,cv=10)
cvs

array([0.9122807 , 0.87719298, 0.89473684, 0.96491228, 0.94736842,
       0.92982456, 0.96491228, 0.92982456, 0.9122807 , 0.96428571])

In [20]:
# see max and min accuracy
cvs.max(),cvs.min()

(0.9649122807017544, 0.8771929824561403)

In [21]:
cvs.mean()

0.9297619047619046