In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("/content/drive/My Drive/DataSets/bangalore house price prediction OHE-data.csv")
df.head()

bath  balcony  ...  location_Mahadevpura  location_Tumkur Road
0   3.0      2.0  ...                     0                     0
1   3.0      3.0  ...                     0                     0
2   3.0      2.0  ...                     0                     0
3   2.0      2.0  ...                     0                     0
4   2.0      2.0  ...                     0                     0

[5 rows x 108 columns]

In [3]:
df.shape

(7120, 108)

In [4]:
df.isnull().sum().any()

False

# Split the features and level

In [5]:
features = df.drop(labels=["price"],axis="columns")
level = df["price"]

In [6]:
features.shape

(7120, 107)

In [7]:
xtrain,xtest,ytrain,ytest = train_test_split(features,level,test_size=0.2,random_state=215)

In [8]:
print('Shape of X_train = ', xtrain.shape)
print('Shape of y_train = ', ytrain.shape)
print('Shape of X_test = ', xtest.shape)
print('Shape of y_test = ', ytest.shape)

Shape of X_train =  (5696, 107)
Shape of y_train =  (5696,)
Shape of X_test =  (1424, 107)
Shape of y_test =  (1424,)


# Apply features scaling

In [9]:
sc = StandardScaler()

In [10]:
x_train = sc.fit_transform(X=xtrain)
x_test = sc.transform(X=xtest)

In [11]:
x_train

array([[-0.45190157, -0.74168307, -0.23130972, ..., -0.05630391,
        -0.05630391, -0.04782807],
       [ 6.4213464 ,  0.0189124 ,  3.69493414, ..., -0.05630391,
        -0.05630391, -0.04782807],
       [-0.45190157, -0.74168307, -0.1325495 , ..., -0.05630391,
        -0.05630391, -0.04782807],
       ...,
       [-0.45190157, -0.74168307, -0.4950205 , ..., -0.05630391,
        -0.05630391, -0.04782807],
       [ 0.69363976,  0.55986903,  0.12275616, ..., -0.05630391,
        -0.05630391, -0.04782807],
       [-0.45190157, -0.74168307, -0.28699367, ..., -0.05630391,
        -0.05630391, -0.04782807]])

## Create the **model**

In [12]:
svm_rbf = SVR(kernel="rbf") # rbf = radial basis function
svm_rbf.fit(x_train,ytrain)
svm_rbf.score(x_test,ytest)

0.2488380163292333

In [13]:
svm_linear = SVR(kernel="linear")
svm_linear.fit(x_train,ytrain)
svm_linear.score(x_test,ytest)

0.7044426151957799

In [14]:
svm_poly = SVR(kernel="poly",degree=2)
svm_poly.fit(x_train,ytrain)
svm_poly.score(x_test,ytest)

0.08221976771145367

In [16]:
pred_one = x_test[0]

In [17]:
svm_linear.predict([pred_one])

array([85.61517661])

In [19]:
ytest.iloc[0]

85.0

In [20]:
y_pred = svm_linear.predict(x_test)
y_pred

array([ 85.61517661,   9.67640241,  49.94802621, ...,  71.78546268,
       136.1126103 ,  85.60757642])

In [21]:
ytest

4158     85.00
1509     16.45
3190     51.00
1035    100.00
6006     60.00
         ...  
386      46.41
4264     53.50
3103     69.00
1763    135.00
2617     84.00
Name: price, Length: 1424, dtype: float64

In [22]:
from sklearn.metrics import mean_squared_error

In [23]:
mse = mean_squared_error(y_true=ytest,y_pred=y_pred)
rmse = np.sqrt(mse)

In [24]:
print(mse)
print(rmse)

4050.8569246755187
63.64634258679377
